name: Test Secrets

on:
  push:
    branches: [ main ]

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check secrets
      env:
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        GHCR_KEY: ${{ secrets.GHCR_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
        ALICLOUD_USERNAME: ${{ secrets.ALICLOUD_USERNAME }}
        ALICLOUD_PASSWORD: ${{ secrets.ALICLOUD_PASSWORD }}
        ALICLOUD_REGISTRY: ${{ secrets.ALICLOUD_REGISTRY }}
        ALICLOUD_NAMESPACE: ${{ secrets.ALICLOUD_NAMESPACE }}
      run: |
        echo "GHCR_USERNAME: $GHCR_USERNAME"
        echo "GHCR_KEY: $GHCR_KEY"
        echo "DOCKER_USERNAME: $DOCKER_USERNAME"
        echo "DOCKER_PASSWD: $DOCKER_PASSWD"
        echo "ALICLOUD_USERNAME: $ALICLOUD_USERNAME"
        echo "ALICLOUD_PASSWORD: $ALICLOUD_PASSWORD"
        echo "ALICLOUD_REGISTRY: $ALICLOUD_REGISTRY"
        echo "ALICLOUD_NAMESPACE: $ALICLOUD_NAMESPACE"
