name: Docker 镜像 CI

on:
  push:
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 构建镜像
      run: |
        REPOSITORY_NAME="napcat"
        IMAGE_TAG="qmsg"
        docker build -t $REPOSITORY_NAME:$IMAGE_TAG .

    - name: 推送到 GitHub 容器注册表
      run: |
        echo "${{ secrets.GHCR_KEY }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
        GHCR_IMAGE_TAG="ghcr.io/${{ secrets.GHCR_USERNAME }}/$REPOSITORY_NAME:$IMAGE_TAG"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG $GHCR_IMAGE_TAG
        docker push $GHCR_IMAGE_TAG

    - name: 推送到 Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        DOCKER_IMAGE_TAG="docker.io/${{ secrets.DOCKER_USERNAME }}/$REPOSITORY_NAME:$IMAGE_TAG"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG $DOCKER_IMAGE_TAG
        docker push $DOCKER_IMAGE_TAG

    - name: 推送到阿里云容器镜像服务
      run: |
        echo "${{ secrets.ALICLOUD_PASSWORD }}" | docker login ${{ secrets.ALICLOUD_REGISTRY }} -u ${{ secrets.ALICLOUD_USERNAME }} --password-stdin
        ALICLOUD_IMAGE_TAG="${{ secrets.ALICLOUD_REGISTRY }}/${{ secrets.ALICLOUD_NAMESPACE }}/$REPOSITORY_NAME:$IMAGE_TAG"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG $ALICLOUD_IMAGE_TAG
        docker push $ALICLOUD_IMAGE_TAG
