name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for amd64
      run: |
        REPOSITORY_NAME="napcat"
        IMAGE_TAG="qmsg"

        # 构建 amd64 架构的镜像
        docker build -t $REPOSITORY_NAME:$IMAGE_TAG-amd64 .

    - name: Build the Docker image for arm64
      run: |
        REPOSITORY_NAME="napcat"
        IMAGE_TAG="qmsg"

        # 构建 arm64 架构的镜像
        docker build -t $REPOSITORY_NAME:$IMAGE_TAG-arm64 .
        
    - name: Login and push images to GitHub Container Registry, Docker Hub, and Alibaba Cloud
      run: |
        REPOSITORY_NAME="napcat"
        IMAGE_TAG="qmsg"

        # 登录到 GitHub Container Registry
        echo $GHCR_KEY | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
        if [ $? -ne 0 ]; then
          echo "登录到 GitHub Container Registry 失败！"
          exit 1
        fi

        # 推送 amd64 架构的镜像到 GitHub Container Registry
        GHCR_IMAGE_TAG_AMD64="ghcr.io/$GHCR_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG-amd64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-amd64 $GHCR_IMAGE_TAG_AMD64
        docker push $GHCR_IMAGE_TAG_AMD64
        if [ $? -eq 0 ]; then
          echo "amd64 架构的镜像推送到 GitHub Container Registry 成功！"
        else
          echo "amd64 架构的镜像推送到 GitHub Container Registry 失败！"
          exit 1
        fi

        # 推送 arm64 架构的镜像到 GitHub Container Registry
        GHCR_IMAGE_TAG_ARM64="ghcr.io/$GHCR_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG-arm64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-arm64 $GHCR_IMAGE_TAG_ARM64
        docker push $GHCR_IMAGE_TAG_ARM64
        if [ $? -eq 0 ]; then
          echo "arm64 架构的镜像推送到 GitHub Container Registry 成功！"
        else
          echo "arm64 架构的镜像推送到 GitHub Container Registry 失败！"
          exit 1
        fi

        # 登录到 Docker Hub
        echo $DOCKER_PASSWD | docker login docker.io -u $DOCKER_USERNAME --password-stdin
        if [ $? -ne 0 ]; then
          echo "登录到 Docker Hub 失败！"
          exit 1
        fi

        # 推送 amd64 架构的镜像到 Docker Hub
        DOCKER_IMAGE_TAG_AMD64="docker.io/$DOCKER_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG-amd64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-amd64 $DOCKER_IMAGE_TAG_AMD64
        docker push $DOCKER_IMAGE_TAG_AMD64
        if [ $? -eq 0 ]; then
          echo "amd64 架构的镜像推送到 Docker Hub 成功！"
        else
          echo "amd64 架构的镜像推送到 Docker Hub 失败！"
          exit 1
        fi

        # 推送 arm64 架构的镜像到 Docker Hub
        DOCKER_IMAGE_TAG_ARM64="docker.io/$DOCKER_USERNAME/$REPOSITORY_NAME:$IMAGE_TAG-arm64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-arm64 $DOCKER_IMAGE_TAG_ARM64
        docker push $DOCKER_IMAGE_TAG_ARM64
        if [ $? -eq 0 ]; then
          echo "arm64 架构的镜像推送到 Docker Hub 成功！"
        else
          echo "arm64 架构的镜像推送到 Docker Hub 失败！"
          exit 1
        fi

        # 登录到阿里云容器镜像服务
        echo $ALICLOUD_PASSWORD | docker login $ALICLOUD_REGISTRY -u $ALICLOUD_USERNAME --password-stdin
        if [ $? -ne 0 ]; then
          echo "登录到阿里云容器镜像服务失败！"
          exit 1
        fi

        # 推送 amd64 架构的镜像到阿里云容器镜像服务
        ALICLOUD_IMAGE_TAG_AMD64="$ALICLOUD_REGISTRY/$ALICLOUD_NAMESPACE/$REPOSITORY_NAME:$IMAGE_TAG-amd64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-amd64 $ALICLOUD_IMAGE_TAG_AMD64
        docker push $ALICLOUD_IMAGE_TAG_AMD64
        if [ $? -eq 0 ]; then
          echo "amd64 架构的镜像推送到阿里云容器镜像服务成功！"
        else
          echo "amd64 架构的镜像推送到阿里云容器镜像服务失败！"
          exit 1
        fi

        # 推送 arm64 架构的镜像到阿里云容器镜像服务
        ALICLOUD_IMAGE_TAG_ARM64="$ALICLOUD_REGISTRY/$ALICLOUD_NAMESPACE/$REPOSITORY_NAME:$IMAGE_TAG-arm64"
        docker tag $REPOSITORY_NAME:$IMAGE_TAG-arm64 $ALICLOUD_IMAGE_TAG_ARM64
        docker push $ALICLOUD_IMAGE_TAG_ARM64
        if [ $? -eq 0 ]; then
          echo "arm64 架构的镜像推送到阿里云容器镜像服务成功！"
        else
          echo "arm64 架构的镜像推送到阿里云容器镜像服务失败！"
          exit 1
        fi
